language: perl
env:
    global:
        - MOARVM="2016.09"
        - NQP="2016.09"
        - RAKUDO="2016.09"
        - REVISION="01"
sudo: required
services:
    - docker
install: true
script:
    - set -e
    - bin/build_pkgrakudo.pl -i nxadm -d docker/Dockerfile-pkgrakudo-centos-amd64-7 && bin/run_pkgrakudo.pl -i nxadm -a amd64 -o centos -v 7 -m $MOARVM -n $NQP -r $RAKUDO -p $REVISION -d /var/tmp
    - bin/build_pkgrakudo.pl -i nxadm -d docker/Dockerfile-pkgrakudo-ubuntu-amd64-16.04 && bin/run_pkgrakudo.pl -i nxadm -a amd64 -o ubuntu -v 16.04 -m $MOARVM -n $NQP -r $RAKUDO -p $REVISION -d /var/tmp
    - bin/build_pkgrakudo.pl -i nxadm -d docker/Dockerfile-pkgrakudo-ubuntu-i386-16.04 && bin/run_pkgrakudo.pl -i nxadm -a i386 -o ubuntu -v 16.04 -m $MOARVM -n $NQP -r $RAKUDO -p $REVISION -d /var/tmp

