language: generic
env:
  global:
  - RAKUDO_VERSION="2018.03"
  - NQP_VERSION="2018.03"
  - MOARVM_VERSION="2018.03"
  - REVISION="99"
  - PATH=/opt/rakudo-pkg/bin:$PATH
  - RAKUDO_DEB="https://github.com/nxadm/rakudo-pkg/releases/download/v2018.02.1/rakudo-pkg-Ubuntu14.04_2018.02.1-01_amd64.deb"
  - secure: "Oa9VgAUAQLiuO2YKGL7LtRDgg3rTfxvsTmkWZpdQbanA0uE1GT+pp2mHwUArvuUBMeCCoftzgNqXjLea+3uTJZfaiojdkxMwxq1/0LO2PqQNQw0HOAK31E8u+aoGhBBmmCW6UgzPxLQUm12FwJvSEOZlhW9Py2sNL/2p1GAM2D9BkA5+0rJZKR9/jhD+z031dXiQctdsJxfZx8KXBEN50P5mKCz2s6jQSlSxBpX4bI82j0mdrjXb1d0SDZVFXQyBXw+kbiCagaxvA1qTQ3kvrtUGHNytfZ7R91A5B4qiKZD8s2BNjZI9nqNLpHqi/IxFBzReSCLEAl8qe3nrgTshyD2rM7TSFWq0wP4Ht+UpbWRJMonYS8o850jFgC7/Zcq+QnRDMHCZIYXe+s1Nnb4oIk5mb49Oq7AeGBOXFfh6F6GK4QVDTHOBK9YX9/3JkwLgppMoK6KqCY9G2jiAAZHlQzfupYkoFXJbxSUx01qSAzPRljShQCOV/qO1pasDMueWBj5bQldzuHFf3hbQVqPIRM3RvG+eiN6+8/hgtUbfnSEmNdIDynQCHKH4Qvx4WGVl7/VEJc9QM1zzjVX16NNLcd0GmFrC/ODAwX53Sp3tHQrD9XJCa19gofptueNQBP9uDT6s539fr0ArEYgGSL1jCCCwblPiZruIiiRpZjTb0wc="
  matrix:
  - OS=alpine   ARCH=amd64 VERSION=3.6
  - OS=alpine   ARCH=amd64 VERSION=3.7
  - OS=centos   ARCH=amd64 VERSION=7
  - OS=debian   ARCH=amd64 VERSION=8 CODENAME=jessie
  - OS=debian   ARCH=amd64 VERSION=9 CODENAME=stretch
  - OS=fedora   ARCH=amd64 VERSION=26
  - OS=fedora   ARCH=amd64 VERSION=27
  - OS=opensuse ARCH=amd64 VERSION=42.3
  - OS=ubuntu   ARCH=amd64 VERSION=14.04 CODENAME=trusty
  - OS=ubuntu   ARCH=amd64 VERSION=16.04 CODENAME=xenial
  - OS=ubuntu   ARCH=amd64 VERSION=17.10 CODENAME=artful
  - OS=ubuntu   ARCH=amd64 VERSION=14.04 CODENAME=trusty
  - OS=ubuntu   ARCH=i386 VERSION=16.04 CODENAME=xenial
  - OS=ubuntu   ARCH=i386 VERSION=17.10 CODENAME=artful
sudo: required
services:
- docker
install: wget $RAKUDO_DEB && sudo dpkg -i *.deb
script:
- bin/create-img.p6 docker/Dockerfile-${OS}-${ARCH}-${VERSION} && bin/create-pkg.p6
  rakudo-pkg/$OS-$ARCH:$VERSION --rakudo-version=$RAKUDO_VERSION --nqp-version=$NQP_VERSION
  --moarvm-version=$MOARVM_VERSION --rev=$REVISION
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: kZZIX3JLoAowpJgQXUheKMquNtnPUNa18SFQQSYaQe3OjaBLzJGuI/Dv+eju3dZA9HWXVVfAl/EBYmx0YRyIa8XPoKL+hxbl29sdcP7wNi4OJsIcYr2dY7dcPY2T1RIWCd2cU7CXbJ1IquDN67asWEBxbpwpZluYDd9odx2JMeMAf2XX+VQjFxwK92hGrpLMdtzNstSiZvYn7inBTOU8nrBxQVccd7ec9ZsF8PUjohazUzpCHYvHgZOPHQZY1UgOD1KlrUmPtUToakDOnXyysZBvC3YBq833eqBXIlaoCELnFdzOnwIQzewxYgXrz4JQQhUmXPIvmylM0MoNp1MnkANs68oECBLvOB8kxOglIYWBad6GtaR5pkLhh3bPwc6fwqZZQMoqlncesKDPtHvmtQmWpWFxbwYsOFgFDcc3jW8DV233EbpubrREbrYFq83Ahc0aYx+GpNWFZ71jlXcErZ7tB/KltHWoCjLPq1dxCIFiq/AOLylK9meo/AQF+RXAb5+3fkd32X5xyRQejYfdhGxZ/c6QkV4C3BAIypJ76Hi0MfePuylMTe4P59nkT98j6ef3d8MtPHIM8DdBww6erseteKCaS0fZaf3e3YBhG9TJYLTHri4o/StCnqTMyiANEcsNoQB3oFC3z5Q76jYHocKo5g+z/6/ooeipn03hKsA=
  file_glob: true
  file: "/var/tmp/rakudo-pkg/*"
  skip_cleanup: true
  on:
    repo: nxadm/rakudo-pkg
    tags: true
    branches:
      only:
        - /^v20\d{2}\.\d{2}(\.\d+)?-\d+$/
  dry_run: true
after_deploy:
  - if [ $OS == 'debian' ] || [ $OS == 'ubuntu' ]; then cd /var/tmp/rakudo-pkg; export FILE=`ls -1 *.deb`; curl -T $FILE -unxadm:$BINTRAY_API "https://api.bintray.com/content/nxadm/rakudo-pkg-debs/rakudo-pkg/${RAKUDO_VERSION}-${REVISION}/pool/main/r/rakudo-pkg/$FILE;deb_distribution=$CODENAME;deb_component=main;deb_architecture=$ARCH;publish=1"; fi
