language: perl
env:
    global:
        - MOARVM="2017.04.2"
        - NQP="2017.04"
        - RAKUDO="2017.04"
        - REVISION="01"
sudo: required
services:
    - docker
install: true
script:
    - set -e
    - bin/create_container.pl -i nxadm -d docker/Dockerfile-pkgrakudo-centos-amd64-7 && bin/pkg_rakudo.pl -i nxadm -a amd64 -o centos -v 7 -m $MOARVM -n $NQP -r $RAKUDO -p $REVISION -d /var/tmp
    - bin/create_container.pl -i nxadm -d docker/Dockerfile-pkgrakudo-ubuntu-amd64-16.04 && bin/pkg_rakudo.pl -i nxadm -a amd64 -o ubuntu -v 16.04 -m $MOARVM -n $NQP -r $RAKUDO -p $REVISION -d /var/tmp
    - bin/create_container.pl -i nxadm -d docker/Dockerfile-pkgrakudo-ubuntu-i386-16.04 && bin/pkg_rakudo.pl -i nxadm -a i386 -o ubuntu -v 16.04 -m $MOARVM -n $NQP -r $RAKUDO -p $REVISION -d /var/tmp
    - bin/create_container.pl -i nxadm -d docker/Dockerfile-pkgrakudo-ubuntu-amd64-16.10 && bin/pkg_rakudo.pl -i nxadm -a amd64 -o ubuntu -v 16.10 -m $MOARVM -n $NQP -r $RAKUDO -p $REVISION -d /var/tmp
    - bin/create_container.pl -i nxadm -d docker/Dockerfile-pkgrakudo-ubuntu-i386-16.10 && bin/pkg_rakudo.pl -i nxadm -a i386 -o ubuntu -v 16.10 -m $MOARVM -n $NQP -r $RAKUDO -p $REVISION -d /var/tmp
    - bin/create_container.pl -i nxadm -d docker/Dockerfile-pkgrakudo-ubuntu-amd64-16.10 && bin/pkg_rakudo.pl -i nxadm -a amd64 -o ubuntu -v 17.04 -m $MOARVM -n $NQP -r $RAKUDO -p $REVISION -d /var/tmp
    - bin/create_container.pl -i nxadm -d docker/Dockerfile-pkgrakudo-ubuntu-i386-16.10 && bin/pkg_rakudo.pl -i nxadm -a i386 -o ubuntu -v 17.04 -m $MOARVM -n $NQP -r $RAKUDO -p $REVISION -d /var/tmp
    - bin/create_container.pl -i nxadm -d docker/Dockerfile-pkgrakudo-fedora-amd64-25 && bin/pkg_rakudo.pl -i nxadm -a amd64 -o fedora -v 25 -m $MOARVM -n $NQP -r $RAKUDO -p $REVISION -d /var/tmp

