language: generic
env:
  global:
    - RAKUDO_VERSION="2017.10"
    - NQP_VERSION="2017.10"
    - MOARVM_VERSION="2017.10"
    - REVISION="01"
    - PATH=/opt/rakudo/bin:$PATH
    - RAKUDO_DEB="https://github.com/nxadm/rakudo-pkg/releases/download/v2017.10/rakudo-Ubuntu14.04_20171000-01_amd64.deb"
  matrix:
    - OS=centos ARCH=amd64 VERSION=7
    - OS=debian ARCH=amd64 VERSION=8
    - OS=debian ARCH=amd64 VERSION=9
    - OS=fedora ARCH=amd64 VERSION=25
    - OS=fedora ARCH=amd64 VERSION=26
    - OS=ubuntu ARCH=amd64 VERSION=14.04
    - OS=ubuntu ARCH=amd64 VERSION=16.04
    - OS=ubuntu ARCH=amd64 VERSION=17.04
    - OS=ubuntu ARCH=amd64 VERSION=17.10
    - OS=ubuntu ARCH=amd64 VERSION=14.04
    - OS=ubuntu ARCH=i386 VERSION=16.04
    - OS=ubuntu ARCH=i386 VERSION=17.04
    - OS=ubuntu ARCH=i386 VERSION=17.10
sudo: required
services:
  - docker
install: wget $RAKUDO_DEB && sudo dpkg -i *.deb
script:
  - sudo bin/create-img.p6 docker/Dockerfile-${OS}-${ARCH}-${VERSION}
  - sudo bin/create-pkg.p6 rakudo-pkg/$OS-$ARCH:$VERSION --rakudo-version=$RAKUDO_VERSION --nqp-version=$NQP_VERSION --moarvm-version=$MOARVM_VERSION --rev=$REVISION
